### ISSUE TITLE
external resources

### ISSUE THREAD

**Issue by cjessett** [andyoliver3/prj-rev-bwfs-dasmoto#1]
(Important) [Here](https://github.com/andyoliver3/prj-rev-bwfs-dasmoto/blob/c8152a261af8e825bfd51321a665ad4ce124514f/Dasmoto's%20Arts/index.html#L11) instead of linking to an external resource, include the image in the project and reference it locally. Since URLs can break or change we include all resources with the project.

**Comment by andyoliver3** [comment]
After completing my earlier projects, I looked at the solution code and it used External URL's when I had selected internal images. I therefore did a Chrome Dev tools inspect of the codeacademy version of this project to see if they used external URL or internal. They used External so I did too. Maybe they should specify ? I would definitely have used an internal folder for images otherwise. 
Thanks for the feedback.
